[package]
name = "sonobe-practice"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = {version="0.4.0", features=["r1cs"]}


[patch.crates-io]
ark-bn254 = { git = "https://github.com/arnaucube/ark-curves-cherry-picked", branch="cherry-pick"}

